management:
  server:
    port: 8081
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health

server:
  shutdown: graceful

springdoc:
  swagger-ui:
    enabled: true

api:
  facebook:
    graph:
      root-url: https://graph.facebook.com/v18.0
    client:
      app-id: app-id
      app-secret: app-secret

spring:
  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: client-id
            client-secret: client-secret
            scope:
              - pages_show_list
              - pages_read_engagement
              - pages_manage_metadata
          google:
            client-id: client-id
            client-secret: client-secret
            scope:
              - email
              - profile
