management:
  server:
    port: 8081
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health

server:
  shutdown: graceful

springdoc:
  swagger-ui:
    enabled: true

api:
  facebook:
    root-url: https://www.facebook.com/v18.0
    dialog-oauth-url: /dialog/oauth
    graph:
      root-url: https://graph.facebook.com/v18.0
      access-token-url: /oauth/access_token
      user-info-url: /me
    client:
      app-id: app-id
      app-secret: app-secret
      scope:
        - profile_nickname
        - account_email

spring:
  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: client-id
            client-secret: client-secret
            scope:
              - email
              - public_profile
          google:
            client-id: client-id
            client-secret: client-secret
            scope:
              - email
              - profile
